name: LTS

on:
  push:
    branches:
    - 'releases/**'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8.12]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: LTS Patch Tagging
        run: |
          git fetch --prune --unshallow --tags
          echo exit code $?
          git tag --list
          RELEASE=${GITHUB_REF##*/}
          echo "LTS version is: $RELEASE"
          git tag -l
          TAG=`git tag -l`
          echo "Most recent tag is $TAG"
          if [ "$TAG" = "" ]; then
            git tag "${RELEASE}.1"
          else
            git tag "${RELEASE}.$((${TAG##*.} + 2))"
          fi
          git push origin --tags
